# Globální nastavení
```{r }
data("mtcars")
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(kableExtra)

theme_set(theme_minimal())
```
# Vyčištění prostředí
```{r }
folder <- "../plots"
unlink(folder, recursive = T)
folder <- paste0(folder, "/")
dir.create(folder)
```
# Sloupcový graf
```{r }
mtcars |>
  mutate(cyl = as.factor(cyl)) |>
  ggplot(aes(x = cyl, y = hp, fill = cyl)) +
  geom_bar(show.legend = F, stat = "summary", fun = mean) +
  theme(panel.grid.major.x = element_blank()) +
  labs(
    title = "Porovnání válců s průměrbou hrubou koňskou silou",
    caption = "Henderson and Velleman (1981)",
    x = "Počet válců",
    y = "Průměrná hrubá koňská síla"
  )

ggsave(paste0(folder, "sloupcovy_graf_mtcars.png"), bg = "white",
       width = 140, height = 105, units = 'mm')
```
# Porovnání histogramů
```{r}
hg <- \(bins) {
  width <- (max(mtcars$mpg) - min(mtcars$mpg))/bins
  width <- ceiling(width)
  mtcars |>
    ggplot(aes(x = mpg)) +
    geom_histogram(binwidth = width) +
    theme(panel.grid.major.x = element_blank(),
          plot.title = element_text(size = 10),
          plot.subtitle  = element_text(size = 8),
          axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8)
          ) +
    labs(
      title = "Histogram míle z galon",
      subtitle = paste0("Počet skupin: ", bins, ", ",
                        "Šířka skupiny: ", round(width, 3)),
      caption = "Henderson and Velleman (1981)",
      x = "Míle za galon",
      y = "Absolutní četnost"
    )
}

h1 <- hg(5)
h2 <- hg(10)
h3 <- hg(15)
h4 <- hg(25)

hg <- arrangeGrob(h1 + labs(caption = ""),
                  h2 + labs(caption = ""),
                  h3 + labs(caption = ""),
                  h4, nrow = 2)

ggsave(paste0(folder, "histogram_porovnani_mtcars.png"),
  plot = hg, bg = "white",
  width = 140, height = 105, units = "mm"
)
```
# Histogram dle Sturgese
```{r}
bins <- ceiling(1 + 3.22*log10(nrow(mtcars)))
width <- (max(mtcars$mpg) - min(mtcars$mpg))/bins
width <- ceiling(width)
hg <- mtcars |>
  ggplot(aes(x = mpg)) +
  geom_histogram(binwidth = width) +
  theme(panel.grid.major.x = element_blank()) +
  labs(
      title = "Histogram míle z galon",
      subtitle = paste0("Počet skupin: ", bins, ", ",
                        "Šířka skupiny: ", round(width, 3)),
      caption = "Henderson and Velleman (1981)",
      x = "Míle za galon",
      y = "Absolutní četnost"
    )
hg
ggsave(paste0(folder, "histogram_mtcars_sturges.png"), bg = "white",
       width = 140, height = 105, units = 'mm')
```
# Histogram dle Sturgese v tabulce
```{r, results='asis'}
ggplot_build(hg)$data[1] |>
  as.data.frame() |>
  select(xmin, xmax, count) |>
  kbl(caption="Tabulka četnostní",
      label = "tabulka_cetnosti_sturges",
      format="latex",
      col.names = c("Spodní hranice intervalu", "Horní hranice intervalu", "Počet pozorování"),
      align="c",
      position = 'H') %>%
  writeLines()
```
# Five-number summary
```{r, results='asis'}
mtcars |>
  summarise(P0   = quantile(wt, probs = 0),
            P25  = quantile(wt, probs = 0.25),
            P50  = quantile(wt, probs = 0.50),
            P75  = quantile(wt, probs = 0.75),
            P100 = quantile(wt, probs = 1)) |>
  kbl(caption = 'Five-number summary tabulka hmotnosti vozidla (lb/1000)',
      label = 'five-number_summary',
      format = 'latex',
      col.names = c('$Q_{0}$', '$Q_{0.25}$',
                    '$Q_{0.50}$', '$Q_{0.75}$',
                    '$Q_{1}$'),
      align = 'c',
      position = 'H',
      escape = F,
      ) |>
  writeLines()
```
# Boxplot
```{r, results='asis'}

mtcars |>
  ggplot(aes(x = as.factor(cyl), y = wt)) +
  geom_boxplot() +
  labs(title = 'Boxplot porovnání všech kategorií počtu válců',
       caption = "Henderson and Velleman (1981)",
       x = 'Počet válců',
       y = 'Hmotnost vozidla (lb/1000)')

ggsave(paste0(folder, "boxplot_mtcars.png"), bg = "white",
       width = 140, height = 105, units = 'mm')
```
# Bodový graf 2d
```{r, results='asis'}
mtcars |>
  ggplot(aes(x = mpg, y = wt)) +
  geom_point() +
  labs(
    title = 'Hmotnost vozidla vysvětlená mílemy za galon',
    subtitle = 'Hmotnost je udaná v (lb/1000)',
    caption = "Henderson and Velleman (1981)",
    x = 'Hmotnost (lb/1000)',
    y = 'Míle za galon'
  )

ggsave(paste0(folder, "bodovy_graf_mtcars.png"), bg = "white",
       width = 140, height = 105, units = 'mm')
```
