---
title: "Analýza esportových dat"
author: "Michal Lauer"
date: "Bakalářská práce"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    df_print: paged
  theme: paper
  highlight: pygments
editor_options: 
  chunk_output_type: inline
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      fig.align = "center", fig.width = 9)
set.seed(12345)
count_na <- \(tbl){
  tbl %>%
    summarise_all(is.na) %>%
    summarise_all(sum) %>%
    pivot_longer(cols = everything(),
                 names_to = "column_name",
                 values_to = "count_of_NAs") %>%
    mutate(percent_ratio = count_of_NAs/nrow(tbl)*100) %>%
    filter(count_of_NAs != 0)
}

```
```{r data-merge}
library(readr)
economy <- read_csv("data/economy.csv",
                    col_select = c("match_id", "event_id"))

players <- read_csv("data/players.csv",
                    col_select = c(""))

picks <- read_csv("data/picks.csv")

results <- read_csv("data/results.csv")



str(players)


```