---
title: "Pomocné grafy pro bakalářskou práci"
author: "Michal Lauer"
date: '2022-04-10'
---
# Globální nastavení
```{r sesetup, message=F}
data("mtcars")
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(kableExtra)
library(GGally)
theme_set(theme_minimal())
```

# Načtení funkcí a dat
```{r data-load}
sapply(list.files("R", pattern = ".R$",
                  full.names = T, recursive = T), source) |>
  invisible()
```

# Sloupcový graf
```{r sloupcovy_graf_mtcars.png}
g <- mtcars |>
  mutate(cyl = as.factor(cyl)) |>
  ggplot(aes(x = cyl, y = hp, fill = cyl)) +
  geom_bar(show.legend = F, stat = "summary", fun = base::mean) +
  theme(panel.grid.major.x = element_blank()) +
  labs(
    title = "Porovnání válců s průměrnou hrubou koňskou silou",
    caption = "Henderson and Velleman (1981)",
    x = "Počet válců",
    y = "Průměrná hrubá koňská síla"
  )

save_bc_picture(.graph = g,
                .file = "sloupcovy_graf_mtcars.png")
g
```

# Porovnání histogramů
```{r histogram_porovnani_mtcars.png}
hg <- \(bins) {
  mtcars |>
    ggplot(aes(x = mpg)) +
    geom_histogram(bins = bins,
                   fill = "grey",
                   color = "black") +
    theme(panel.grid.major.x = element_blank(),
          plot.title = element_text(size = 10),
          plot.subtitle  = element_text(size = 8),
          axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8)
    ) +
    labs(
      title = "Histogram míle za galon",
      subtitle = paste0("Počet skupin: ", bins),
      caption = "Henderson and Velleman (1981)",
      x = "Míle za galon",
      y = "Absolutní četnost"
    )
}

h1 <- hg(5)
h2 <- hg(10)
h3 <- hg(15)
h4 <- hg(25)

g <- arrangeGrob(h1 + labs(caption = ""),
                 h2 + labs(caption = ""),
                 h3 + labs(caption = ""),
                 h4, nrow = 2)

save_bc_picture(.graph = g, 
                .file = "histogram_porovnani_mtcars.png")
grid.draw(g)
```

# Histogram dle Sturgese
```{r histogram_mtcars_sturges.png}
bins <- ceiling(1 + 3.22*log10(nrow(mtcars)))
width <- (max(mtcars$mpg) - min(mtcars$mpg))/bins
width <- ceiling(width)
g <- mtcars |>
  ggplot(aes(x = mpg)) +
  geom_histogram(binwidth = width,
                 fill = "grey",
                 color = "black") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  labs(
    title = "Histogram míle za galon",
    subtitle = paste0("Počet skupin: ", bins, ", ",
                      "Šířka skupiny: ", round(width, 3)),
    caption = "Henderson and Velleman (1981)",
    x = "Míle za galon",
    y = "Absolutní četnost"
  )

save_bc_picture(.graph = g, 
                .file = "histogram_mtcars_sturges.png")
```

# Five-number summary
```{r five-number_summary, results='asis'}
mtcars |>
  summarise(P0   = quantile(wt, probs = 0),
            P25  = quantile(wt, probs = 0.25),
            P50  = quantile(wt, probs = 0.50),
            P75  = quantile(wt, probs = 0.75),
            P100 = quantile(wt, probs = 1)) |>
  kbl(caption = 'Five-number summary tabulka hmotnosti vozidla (lb/1000)',
      label = 'five-number_summary',
      format = 'latex',
      col.names = c('$Q_{0}$', '$Q_{0.25}$',
                    '$Q_{0.50}$', '$Q_{0.75}$',
                    '$Q_{1}$'),
      align = 'c',
      position = 'H',
      escape = F,
  ) |>
  writeLines()
```

# Krabičkový graf
```{r krabickovy_graf_mtcars.png}
g <-  mtcars |>
  ggplot(aes(x = as.factor(cyl), y = wt)) +
  geom_boxplot(outlier.shape = 1) +
  theme(
    panel.grid.major.x = element_blank()
  ) +
  labs(title = 'Krabičkový graf hmotnosti vozidla (lb/1000) přes kategorie válců',
       caption = "Henderson and Velleman (1981)",
       x = 'Počet válců',
       y = 'Hmotnost vozidla (lb/1000)')

save_bc_picture(.graph = g,
                .file = "krabickovy_graf_mtcars.png")
g
```

# Bodový graf 2d
```{r bodovy_graf_mtcars.png}
g <- mtcars |>
  ggplot(aes(x = mpg, y = wt)) +
  geom_point() +
  labs(
    title = 'Hmotnost vozidla vysvětlená mílemi za galon',
    subtitle = 'Hmotnost je udaná v (lb/1000)',
    caption = "Henderson and Velleman (1981)",
    x = 'Míle za galon',
    y = 'Hmotnost (lb/1000)',
  )

save_bc_picture(.graph = g,
                .file = "bodovy_graf_mtcars.png")
g
```

# Korelační matice
```{r mtcars_korelace.png}
g <- mtcars |> 
  select(where(is.numeric)) |> 
  ggcorr(label = T) +
  labs(
    title = "Korelace mezi kvantitativními proměnnými",
    caption = "Dataset: mtcars"
  )

save_bc_picture(.graph = g,
                .file = "mtcars_korelace.png")
g
```